---
- name: Check if 'java' is on the PATH
  shell: which java
  register: which_java_cmd
  ignore_errors: yes
  become: yes

- name: Install package 'java-1.8.0-openjdk'
  yum:
    pkg: java-1.8.0-openjdk
    state: present
  register: java_install
  ignore_errors: yes
  when: which_java_cmd.rc != 0
  become: yes